### PR TITLE
Add compilation flags for compiling for MIPS CPU Architecture.

### PR DESCRIPTION
**Pull request by Dvineone**
Added Complilation flags to compile on MIPS router CPU's Testing and working with OpenWRT/MIPS24kc Architecture

Issues Noticed. CPU runs high and speedtest only show 5 Mb of bandwidth due to CPU load maxed out. Looking into fix

### CODE REVIEW

**Comment by Dvineone** [comment]
Screenshot from 2021-08-27 22-00-04

Attaching a screen shot of engarde running on single core router as you can see it is using a majority of the CPU. I am currently running a 720p live stream through it. If you have any idea's on how to lower the load please let me know or patch

Thank you
Dvineone

**Comment by ale-rinaldi** [comment]
Hello,

First of all, thanks for contributing!

The high CPU consumption is something that happens on any architecture; of course if the CPU power is higher you most likely won't notice it. On my laptop I start noticing a bottleneck on about 30Mbps. I still haven't dealt with it since I personally use engarde only to transfer audio streams, so with low throughtput. I will, however, try to find a better approach to reduce the CPU usage.

As per your merge request, I have a doubt only: the little endian and big endian lines seem identical to me. Is this a typo?

Thanks

**Comment by Dvineone** [comment]
Yes. Looks like it is. I will fix it and repush.

**Comment by Dvineone** [comment]
Added second commit with the correct OSARCH variable for MIPS little endian flag

**Comment by ale-rinaldi** [comment]
Thank you @Dvineone , I will merge this in a branch to complete the build commands (for server, too) and to add the download links to the README. I'll then merge in master.

**Pull request merged**
